# Generated by Django 4.0.3 on 2022-03-12 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_wallets_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='id',
        ),
        migrations.AlterField(
            model_name='wallets',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
