# Generated by Django 4.0.3 on 2022-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount_money',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='money_rest',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
