# Generated by Django 4.0.3 on 2022-03-13 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transactions_amount_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
