# Generated by Django 4.0.3 on 2022-03-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_wallets_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date',
            new_name='date_provided',
        ),
    ]
