# Generated by Django 4.0.3 on 2022-03-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transactions_wallets_to_pay_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='wallets_to_pay',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='wallets_to_pay_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallets', to='transactions.wallets'),
        ),
    ]
