# Generated by Django 4.0.3 on 2022-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_rename_wallets_to_pay_new_transactions_wallets_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount_money',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
