# Generated by Django 4.0.3 on 2022-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transactions_amount_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='money_rest',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
