# Generated by Django 4.0.3 on 2022-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_wallets_money_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount_money',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='money_rest',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
