# Generated by Django 4.0.3 on 2022-03-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_transactions_amount_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='wallets_to_pay',
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallets_to_pay_new',
            field=models.ManyToManyField(through='transactions.Link', to='transactions.wallets'),
        ),
        migrations.AddField(
            model_name='link',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transactions'),
        ),
        migrations.AddField(
            model_name='link',
            name='wallets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.wallets'),
        ),
    ]
