# Generated by Django 4.0.3 on 2022-03-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_link_remove_transactions_wallets_to_pay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='wallets_to_pay_new',
            new_name='wallets_to_pay',
        ),
    ]
