# Generated by Django 4.0.3 on 2022-03-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_rename_wallets_to_pay_new_transactions_wallets_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
