# Generated by Django 4.0.3 on 2022-03-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_link_transactions_alter_link_wallets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transactions', verbose_name='Транзакция'),
        ),
        migrations.AlterField(
            model_name='link',
            name='wallets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.wallets', verbose_name='Кошелёк'),
        ),
    ]
