# Generated by Django 4.0.3 on 2022-03-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_link_transactions_alter_link_wallets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-date_provided']},
        ),
        migrations.AlterModelOptions(
            name='wallets',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='link',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions', verbose_name='Транзакция'),
        ),
    ]
