# Generated by Django 4.0.3 on 2022-03-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_transaction_recipient_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient_wallet',
            field=models.ForeignKey(help_text='Введите имя пользователя или почту получателя', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_wallet', to='transactions.wallet', verbose_name='Кошелёк получателя'),
        ),
    ]
