# Generated by Django 4.0.3 on 2022-03-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_alter_transaction_recipient_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='transactions',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='wallets',
            new_name='wallet',
        ),
    ]
